variable "subnetAid" {}
variable "subnetBid" {}
variable "subnetCid" {}
variable "subnetUid" {}
variable "subnetACIDR" {}
variable "subnetBCIDR" {}
variable "subnetCCIDR" {}
variable "subnetDCIDR" {}
variable "subnetUCIDR" {}
variable "splunk-ami" {}
variable "splunk_instance_type" {}
variable "vpc_id" {}
variable "splunk_web_port" {}
variable "splunk_mgmt_port" {}
variable "key_name" {}
variable "splunk_license_bucket" {}
variable "splunk_license_file" {}
variable "project_name" {}
variable "gtos_gmnts_landing" {}
variable "ec2_ami" {}
variable "bastion_instance_type" {}
variable "accessip" {}
variable "splunk_license_file_path" {}
variable "bastion_windows_name" {}