variable "subnetAid" {}
variable "subnetBid" {}
variable "subnetCid" {}
variable "subnetDid" {}
variable "subnetUid" {}
variable "subnetACIDR" {}
variable "subnetBCIDR" {}
variable "subnetCCIDR" {}
variable "subnetDCIDR" {}
variable "subnetUCIDR" {}
variable "splunk-ami" {}
variable "splunk_instance_type" {}
variable "vpc_id" {}
variable "splunk_web_port" {}
variable "splunk_mgmt_port" {}
variable "key_name" {}
variable "splunk_license_bucket" {}
variable "splunk_license_file" {}
variable "project_name" {}
variable "gtos_gmnts_landing" {}
variable "ec2_ami" {}
variable "bastion_instance_type" {}
variable "accessip" {
  type = list(string)
}
variable "splunk_license_file_path" {}
variable "bastion_windows_name" {}
variable "spot_price" {}
variable "endpoint_service_name" {}
variable "gtos_private_route_table_id" {}
variable "splunk_license_master_key" {}
variable "ec2_user" {}
variable "bastion_user" {}
variable "bastion_key" {}
variable "splunk_admin_pass" {}
variable "enable_nat_instance" {
  type = bool
}
